name: CI

on:
  push:
    branches: [main]  # Runs on all pushes to 'main'
    tags:
      - "*"           # Runs on all tags (no "v" required)
  pull_request:
    branches: [main]  # Runs on PRs targeting 'main'
  workflow_dispatch:   # Allows manual execution

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check Rust Formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo Build
        run: cargo build --release

      - name: Git Describe
        run: git describe --tags --always --dirty

      - name: Cargo Run
        run: cargo run --release --quiet || (echo "Cargo run failed" && exit 1)

      - name: Run Self-Tests
        run: make test


