name: CI

on:
  push:
    branches: [main]  # Runs on all pushes to 'main'
    tags:
      - "*"           # Runs on tag pushes
  pull_request:
    branches: [main]  # Runs on PRs targeting 'main'
  workflow_dispatch:  # Allows manual execution

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ensure Cargo.toml version matches Git describe
        run: |
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          GIT_VERSION=$(git describe --tags --always --dirty)
          echo "Cargo.toml version: $CARGO_VERSION"
          echo "Git describe version: $GIT_VERSION"
          if ! echo "$GIT_VERSION" | grep -q "^$CARGO_VERSION"; then
            echo "::warning file=Cargo.toml,line=1,col=1::Version mismatch! Cargo.toml ($CARGO_VERSION) does not match Git describe ($GIT_VERSION)"
          fi

      - name: Check Rust Formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Cargo Build
        run: cargo build --release

      - name: Run Cargo Tests
        run: cargo test --release --quiet

      - name: Run Binary
        run: |
          output=$(cargo run --release --quiet)
          echo "Cargo output: $output"
          if echo "$output" | grep -q -- '-dirty'; then
            echo "CI build should not be dirty!"
            exit 1
          fi

      - name: Run Self-Tests
        run: make test

      - name: Ensure working tree is clean after build
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "The build modified files!"
            git status
            exit 1
          fi

      - name: Cache Build Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/cache@v4
        with:
          path: target/release
          key: release-${{ github.sha }}

  verify-release:
    needs: build-and-test  # Ensures this only runs if the build succeeds
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Restore Build Artifacts
        uses: actions/cache@v4
        with:
          path: target/release
          key: release-${{ github.sha }}

      - name: Verify Git Tag Matches Cargo Version
        run: |
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          GIT_TAG=$(git describe --tags --exact-match || echo "untagged")
          echo "Cargo.toml version: $CARGO_VERSION"
          echo "Git tag: $GIT_TAG"
          if [[ "$GIT_TAG" != "$CARGO_VERSION" ]]; then
            echo "Error: Tag ($GIT_TAG) does not match Cargo.toml version ($CARGO_VERSION)!"
            exit 1
          fi

      - name: Ensure working tree is clean after tag creation
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Tagging process introduced uncommitted changes!"
            git status
            exit 1
          fi
