name: Verify Tag

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  verify-release-tag:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Verify Git Tag Matches Cargo Version
        run: |
          TAG=$(git describe --tags --exact-match || echo "untagged")
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')

          echo "Cargo.toml version: $CARGO_VERSION"
          echo "Git tag: $TAG"

          if [[ "$TAG" != "$CARGO_VERSION" ]]; then
            echo "Error: Tag ($TAG) does not match Cargo.toml version ($CARGO_VERSION)!"
            exit 1
          fi

      - name: Ensure working tree is clean after tag creation
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Tagging process introduced uncommitted changes!"
            git status
            exit 1
          fi
